### ISSUE TITLE
PPC64 big endian support?

### ISSUE THREAD

**Issue by Link4Electronics** [runlevel5/lwjgl3-ppc64le-release#1]
Hello mate, I hope everything is okay. I'm trying to compile lwjgl3 on a PPC64 big endian machine, but when trying to `ant compile-templates` I'm getting segmentation fault, I wonder if you have an ideas that could help to make it to compile on big endian? I already filled an issue [here](https://github.com/LWJGL/lwjgl3/issues/1021) but no answer so far.

Best regards,
Link.

**Comment by runlevel5** [comment]
@Link4Electronics hey how are you? I have _NOT_ attempted to compile the library on PPC64BE. I think it is going to be HARD because there are so many components of lwjgl3 that needs to be patched to get PPC64BE properly supported. Let's keep the focus on the issue you opened upstream. If I could manage to get them working on BE, I will let you know
